### PR TITLE
feat: collect emails subscriber schema file added

### PR DESCRIPTION
**Pull request by transcendence12**
- create schema for subscriber

### CODE REVIEW

**Comment by transcendence12** [comment]
To do: UI

**Comment by transcendence12** [comment]
- installed bridger.to from `https://components.bridger.to/start`
- installed dependencies
- added component `components/ctas/cta-two`

**Review by meczajkowski — APPROVED** [review]
Looks good!

**Comment by meczajkowski** [comment]
- Found some use case for utilizing SanityFetch method and implemented it. 
- Deploy error caused by difference in env files

**Pull request merged**
